name: Demo
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  demo:
    name: Demo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Demo
        uses: .